# Generated by Django 4.0.1 on 2022-01-10 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.thing')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.thing')),
            ],
        ),
    ]
